apiVersion: v1
kind: ConfigMap
metadata:
  name: statuspage-config
  namespace: statuspage
data:
  DB_NAME: "statuspage"
  DB_USER: "statuspage"
  DB_HOST: "postgres.statuspage.svc.cluster.local"
  REDIS_HOST: "redis.statuspage.svc.cluster.local"
  REDIS_PORT: "6379"

