name: build test and push docker image to ecr

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: status-page
          POSTGRES_USER: statuspage
          POSTGRES_PASSWORD: statuspage
        ports: [5432:5432]
        options: >- # checks connections check every 10 seconds timeout of 5 seconds retries 5
          --health-cmd "pg_isready -U statuspage"  
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:4.0
        ports: [6379:6379]
        options: >- #  redis-cli ping  check connection to container check every 10 seconds timines 5 retries 5
          --health-cmd "redis-cli ping" 
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: build image
      run: docker build -f ./Application/Dockerfile ./Application --tag statuspage:latest
    - name: run container
      run: |
        docker run -d \
          --name test-container \
          --network host \
          -e DB_HOST=localhost \
          -e DB_PORT=5432 \
          -e DB_USER=statuspage \
          -e DB_PASSWORD=statuspage \
          -e DB_NAME=status-page \
          statuspage:latest
    - name: Test container
      run: |
        sleep 15
        docker ps -a
        docker logs test-container
        curl --fail --retry 5 --retry-delay 3 --retry-connrefused http://localhost:8000 || exit 1
    - name: Stop container
      run: docker stop test-container

  ecr:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push to ECR
      run: |
        docker build -f ./Application/Dockerfile ./Application --tag ${{ steps.login-ecr.outputs.registry }}/nach-hi/statuspage:${{ github.sha }}
        docker push ${{ steps.login-ecr.outputs.registry }}/nach-hi/statuspage:${{ github.sha }}